services:
  django:
    image: ${DJANGO_PROJECT}:${DJANGO_TAG}
    build:
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - 8020:8020
    env_file: .env
    secrets:
      - django-postgres
    volumes:
      - ./django:/opt/app/django
      - ./.pip_cache:/opt/app/pip_cache

  db:
    image: postgres:15-alpine
    restart: always
    env_file: .env
    ports:
      - "5432:5432"
    secrets:
      - postgres
    volumes:
      - dbdata:/var/lib/postgresql/data

  adminer:
    image: adminer:4
    restart: always
    ports:
      - 8021:8080

  pgadmin:  
    image: dpage/pgadmin4
    env_file: .env
    depends_on:
      - db
    ports:
      - "8022:80"

secrets:
  postgres:
    file: ./secrets/postgres.passwd
  django-postgres:
    file: ./secrets/django-postgres.passwd

volumes:
  dbdata:
