version: '2'
services:
  db:
    image: postgres
  web:
    build: .
    environment:
      - PARALLEL_MODE
    command: /start.sh
    volumes:
      - ./code:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
